[versions]
agp = "8.7.3"
kotlin = "1.9.24"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
app_compat = "1.7.0"
android_junit = "1.1.5"
work = "2.10.0"
compose = "1.4.2"
coroutines = "1.7.3"
retrofit = "2.9.0"
nav = "2.8.9"
media3 = "1.6.0"
room = "2.5.2"
okhttp = "5.0.0-alpha.10"
uiAndroid = "1.9.3"
material3Android = "1.4.0"
preference = "1.2.1"

adjustAndroid = "4.33.1"
firebaseConfig = "22.0.1"

[libraries]
adjust-android = { module = "com.adjust.sdk:adjust-android", version.ref = "adjustAndroid" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version = "1.0.0" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.4.0" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version = "retrofit" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
firebase-config = { group = "com.google.firebase", name = "firebase-config", version.ref = "firebaseConfig" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version = "8.5.2" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.0.21" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version = "2.0.21" }
kspp = { id = "com.google.devtools.ksp", version = "2.0.21-1.0.28" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1" }
